# Tyeps: Domain / URL / IPv4 / IPv6 / Email
# Date Format: '%Y-%m-%d %H:%M:%S'
# "update_frequency" should be in seconds

lists = [
    {
    'name':'Adway',
    'type':'Domain',
    'url':'https://adaway.org/hosts.txt',
    'category': 'Adware',
    'latest_load':'2020-12-15 00:00:00',
    'update_frequency':'86400',
    'data':'',
    },
    # {
    # 'name':'Malware Domains',
    # 'type':'Domain',
    # 'url':'http://mirror1.malwaredomains.com/files/justdomains',
    # 'category': 'Malware',
    # 'latest_load':'2020-12-15 00:00:00',
    # 'update_frequency':'86400',
    # 'data':'',
    # },
    # {
    # 'name':'Mal C0de',
    # 'type':'Domain',
    # 'url':'http://malc0de.com/bl/ZONES',
    # 'category': 'Malware',
    # 'latest_load':'2020-12-15 00:00:00',
    # 'update_frequency':'86400',
    # 'data':'',
    # },
    # {
    # 'name':'Yoyo',
    # 'type':'Domain',
    # 'url':'https://pgl.yoyo.org/adservers/serverlist.php?hostformat=nohtml',
    # 'category': 'Adware',
    # 'latest_load':'2020-12-15 00:00:00',
    # 'update_frequency':'86400',
    # 'data':'',
    # }, 
    # {
    # 'name':'Ad Block +',
    # 'type':'Domain',
    # 'url':'https://easylist-downloads.adblockplus.org/malwaredomains_full.txt',
    # 'category': 'Malware',
    # 'latest_load':'2020-12-15 00:00:00',
    # 'update_frequency':'86400',
    # 'data':'',
    # },
    # {
    # 'name':'URLhaus',
    # 'type':'Domain',
    # 'url':'https://curben.gitlab.io/malware-filter/urlhaus-filter.txt',
    # 'category': 'Malware',
    # 'latest_load':'2020-12-15 00:00:00',
    # 'update_frequency':'86400',
    # 'data':'',
    # },
    # {
    # 'name':'URLhaus',
    # 'type':'Domain',
    # 'url':'https://curben.gitlab.io/phishing-filter-mirror/phishing-filter.txt',
    # 'category': 'Phishing',
    # 'latest_load':'2020-12-15 00:00:00',
    # 'update_frequency':'86400',
    # 'data':'',
    # },
    # {
    # 'name':'URLhaus',
    # 'type':'URL',
    # 'url':'https://gitlab.com/curben/tracking-data/-/raw/master/dist/tracking-data.txt',
    # 'category': 'Tracker',
    # 'latest_load':'2020-12-15 00:00:00',
    # 'update_frequency':'86400',
    # 'data':'',
    # },
    # {
    # 'name':'NoTrack',
    # 'type':'Domain',
    # 'url':['https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt','https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt'],
    # 'category': 'Multi',
    # 'latest_load':'2020-12-15 00:00:00',
    # 'update_frequency':'86400',
    # 'data':'',
    # },
    # {
    # 'name':'NoTrack',
    # 'type':'Domain',
    # 'url':'https://gitlab.com/quidsup/notrack-annoyance-blocklist/-/raw/master/notrack-annoyance.txt',
    # 'category': 'Annoyance',
    # 'latest_load':'2020-12-15 00:00:00',
    # 'update_frequency':'86400',
    # 'data':'',
    # },
    # {
    # 'name':'hBlock',
    # 'type':'Domain',
    # 'url':'https://hblock.molinero.dev/hosts_domains.txt',
    # 'category': 'Malware',
    # 'latest_load':'2020-12-15 00:00:00',
    # 'update_frequency':'86400',
    # 'data':'',
    # },
    # {
    # 'name':'hBlock',
    # 'type':'Domain',
    # 'url':'https://hblock.molinero.dev/hosts_adblock.txt',
    # 'category': 'Adware',
    # 'latest_load':'2020-12-15 00:00:00',
    # 'update_frequency':'86400',
    # 'data':'',
    # },
    # {
    # 'name':'Cedia',
    # 'type':'Domain',
    # 'url':'https://mirror.cedia.org.ec/malwaredomains/temp.spywaredomains.zones', # it is old
    # # 'url':'https://mirror.cedia.org.ec/malwaredomains/spywaredomains.zones.zip', # it is new but zip
    # 'category': 'Spyware',
    # 'latest_load':'2020-12-15 00:00:00',
    # 'update_frequency':'86400',
    # 'data':'',
    # },
    # {
    # 'name':'Open Phish',
    # 'type':'URL',
    # 'url':'https://openphish.com/feed.txt',
    # 'category': 'Phishing',
    # 'latest_load':'2020-12-15 00:00:00',
    # 'update_frequency':'86400',
    # 'data':'',
    # },
    # {
    # 'name':'ABP Indo',
    # 'type':'Domain',
    # 'url':'https://raw.githubusercontent.com/dead-hosts/indonesianadblockrules-validate-hosts_git_ABPindo/master/output/hosts/ACTIVE/hosts',
    # 'category': 'Adware',
    # 'latest_load':'2020-12-15 00:00:00',
    # 'update_frequency':'86400',
    # 'data':'',
    # },
    # {
    # 'name':'Joe Wein',
    # 'type':'Domain',
    # 'url':['http://www.joewein.net/dl/bl/dom-bl-base.txt','http://www.joewein.net/dl/bl/dom-bl.txt'],
    # 'category': 'Spam',
    # 'latest_load':'2020-12-15 00:00:00',
    # 'update_frequency':'86400',
    # 'data':'',
    # },
    # {
    # 'name':'Taz',
    # 'type':'Domain',
    # 'url':['http://www.taz.net.au/Mail/SpamDomains','http://www.taz.net.au/Mail/body_checks.domains'],
    # 'category': 'Spam',
    # 'latest_load':'2020-12-15 00:00:00',
    # 'update_frequency':'86400',
    # 'data':'',
    # },
    # {
    # 'name':'Taz',
    # 'type':'IPv4',
    # 'url':'http://www.taz.net.au/Mail/body_checks.ip-addresses',
    # 'category': 'Spam',
    # 'latest_load':'2020-12-15 00:00:00',
    # 'update_frequency':'86400',
    # 'data':'',
    # },
    # {
    # 'name':'Abuse CH',
    # 'type':'Domain_IPv4',
    # 'url':'https://urlhaus.abuse.ch/downloads/csv_recent/',
    # 'category': 'Malware',
    # 'latest_load':'2020-12-15 00:00:00',
    # 'update_frequency':'86400',
    # 'data':'',
    # },
    # {
    # 'name':'Emerging Threats',
    # 'type':'IPv4',
    # 'url':'http://rules.emergingthreats.net/blockrules/emerging-tor.rules',
    # 'category': 'TOR',
    # 'latest_load':'2020-12-15 00:00:00',
    # 'update_frequency':'86400',
    # 'data':'',
    # },
    # {
    # 'name':'Abuse CH',
    # 'type':'IPv4',
    # 'url':['https://sslbl.abuse.ch/blacklist/sslipblacklist.csv', 'https://feodotracker.abuse.ch/downloads/ipblocklist_recommended.txt'],
    # 'category': 'Botnet',
    # 'latest_load':'2020-12-15 00:00:00',
    # 'update_frequency':'86400',
    # 'data':'',
    # },
    {
    'name':'BlockList.de',
    'type':'IPv4',
    'url':'http://lists.blocklist.de/lists/all.txt',
    'category': 'Malicious Activity',
    'latest_load':'2020-12-15 00:00:00',
    'update_frequency':'86400',
    'data':'',
    },
    {
    'name':'CleanTalk',
    'type':'IPv4',
    'url':'https://iplists.firehol.org/files/cleantalk_7d.ipset',
    'category': 'Spam',
    'latest_load':'2020-12-15 00:00:00',
    'update_frequency':'86400',
    'data':'',
    },
    {
    'name':'VoIP Blacklist',
    'type':'IPv4',
    'url':'http://www.voipbl.org/update',
    'category': 'VoIP Fraud',
    'latest_load':'2020-12-15 00:00:00',
    'update_frequency':'86400',
    'data':'',
    },
    {
    'name':'Firehol',
    'type':'IPv4',
    'url':'https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/firehol_level4.netset',
    'category': 'Malware',
    'latest_load':'2020-12-15 00:00:00',
    'update_frequency':'86400',
    'data':'',
    },
    {
    'name':'Cybercrime Tracker',
    'type':'Domain_IPv4',
    'url':'http://cybercrime-tracker.net/all.php',
    'category': 'Malware',
    'latest_load':'2020-12-15 00:00:00',
    'update_frequency':'86400',
    'data':'',
    },
]
